[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NODE_OPTIONS = "--max_old_space_size=8192"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "0"
